name: Run All End 2 End test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - prod

jobs:
  tests-api:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Check out git repo
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Run test
        run: |
          docker compose -f docker-compose.e2e.yml up --build --exit-code-from e2e
