name: dev

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev
      - predeploy

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 Check out git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install package dependence
        run: npm run
